import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { useState } from 'react'

const url = 'https://script.google.com/macros/s/AKfycbyKvR3ItrKxt3Kc7CmjxfCm67AkBpklfU6bnvfkgScHZTa_L0PysGDp0PtGQbreTus5/exec'

export default function Home() {
  const [name, setName] = useState('')
  const [month, setMonth] = useState('0')
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div style={{ display: 'inline' }}>
          <label>Name</label>
          <input value={name} onChange={ev => setName(ev.target.value)} />
          <label>Month</label>
          <input value={month} type={'number'} min={0} max={12} onChange={ev => setMonth(ev.target.value)} />
          <button onClick={() => {
            fetch(`${url}?name=${name}&month=${month}`)
          }}>Send</button>
        </div>
      </main>
    </>
  )
}
